spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: bookdb

mongock:
  runner-type: "ApplicationRunner"
  change-logs-scan-package:
    - ru.otus.spring08homework.mongock.changelogs
  mongo-db:
    write-concern:
      journal: false
    read-concern: local

logging:
  level:
    root: ERROR