spring:
  datasource:
    url: jdbc:h2:mem:bookdb
    driverClassName: org.h2.Driver

    hibernate:
      ddl-auto: none

  liquibase:
    enabled: true
    drop-first: true

  main:
    allow-circular-references: true

  batch:
    job:
      enabled: false
  shell:
    interactive:
      enabled: true

  mongodb:
    embedded:
      version: 3.4.0

  data:
    mongodb:
      host: localhost
      port: 27017
      database: BookDB
  h2:
    console:
      enabled: true
      path: /h2-console

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.spring14homework.mongock.changelogs
  mongo-db:
    write-concern:
      journal: false
    read-concern: local
