
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: bookdb

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.spring11homework.mongock.changelogs
  mongo-db:
    write-concern:
      journal: false
    read-concern: local
