spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: none

  liquibase:
    enabled: true
    drop-first: true

