spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: postgres
    password: postgres
  jpa:
    show-sql: true

    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format-sql: true

  liquibase:
    enabled: true
    drop-first: true

  mvc:
    hiddenmethod:
      filter:
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: metrics,prometheus,health,logfile,info
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true
  info:
    env:
      enabled: true

info:
  version: @project.version@
  author: eu.vaganov
  descriptiion: library app

logging:
  file:
    name: logs/logfile.log
  logback:
    rollingpolicy:
      file-name-pattern: logs/logfile_%d{yyyy-MM-dd}_%i.log
      max-file-size: 10MB
      max-history: 10
      clean-history-on-start: true
