spring:
  datasource:
    url: jdbc:h2:mem:bookdb

  jpa:
    show-sql: true

    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format-sql: true

  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true
  liquibase:
    enabled: true
    drop-first: true

  mvc:
    hiddenmethod:
      filter:
        enabled: true